// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEcmZzn9qxcOkzSIb16k3isVu0jYNNes8',
    appId: '1:521397787794:web:5a508cf8723e320633da4b',
    messagingSenderId: '521397787794',
    projectId: 'event-ae995',
    authDomain: 'event-ae995.firebaseapp.com',
    storageBucket: 'event-ae995.appspot.com',
    measurementId: 'G-Z12PKBSCYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8QKBNmawOoEhMQYg-GpmUVBOKBF8NAFA',
    appId: '1:521397787794:android:14edab32173fae0333da4b',
    messagingSenderId: '521397787794',
    projectId: 'event-ae995',
    storageBucket: 'event-ae995.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEcmZzn9qxcOkzSIb16k3isVu0jYNNes8',
    appId: '1:521397787794:web:15a36dcd6b2dd2d433da4b',
    messagingSenderId: '521397787794',
    projectId: 'event-ae995',
    authDomain: 'event-ae995.firebaseapp.com',
    storageBucket: 'event-ae995.appspot.com',
    measurementId: 'G-RRGTYZLH2B',
  );

}